--- 
# Create the elastic namespace 
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    chart: {{ include "efkv2-aks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}